### ISSUE TITLE
API endpoint is hardcoded, but zeptomail is using a different endpoint for EU customers

### ISSUE THREAD

**Issue by linobino1** [infinitizon/nodemailer-zeptomail-transport#1]
The EU hostname is api.zeptomail.eu instead of  zeptomail.zoho.com, there might be more regional hosts, I'm not sure.

I think there should be a way to define the hostname during initialization, maybe let zeptomail.zoho.com as default value.

In my case, requests fail with a misleading error message:

```
"Error while sending email to address: leo.hilsheimer@gmail.com. Email not sent: {\"error\":{\"code\":\"TM_4001\",\"details\":[{\"code\":\"SERR_157\",\"message\":\"Invalid API Token found\"}],\"message\":\"Access Denied\"}}"
```

I will try to make a PR tomorrow, thanks for uploading this little helper anyways.

**Comment by infinitizon** [comment]
Oh great! 
Thanks for the notice. I'd appreciate the PR.
Cheers

**Comment by linobino1** [comment]
Done https://github.com/infinitizon/nodemailer-zeptomail-transport/pull/2

**Comment by linobino1** [comment]
🙏
it's live in version 1.0.13
